### ISSUE TITLE
我愿意维护

### ISSUE THREAD

**Issue by baiyoulong** [armaab/hyperlpr-train#12]
不知道需要什么条件？

**Comment by armaab** [comment]
没啥条件，只要知道咋回事就行了。你Fork过去，然后我在我这放个你的链接。

**Comment by baiyoulong** [comment]
好的，懂了。已经fork了。

**Comment by baiyoulong** [comment]
下一步做什么？请指教。

**Comment by Kevin-SJW** [comment]
想请教大佬，将lprlite中的gru部分移植到训练代码中，在y_pred的维度控制上一直存在问题，可以公布一个gru+ctc训练的版本吗？
