### ISSUE TITLE
https://gitbook.cn/gitchat/activity/5c9c902ddd42c631eb85beed

### ISSUE THREAD

**Issue by hoolang** [armaab/hyperlpr-train#17]
https://gitbook.cn/gitchat/activity/5c9c902ddd42c631eb85beed
这个里面有写CNN+CTC+GRU的验证码训练和识别，稍微改下就变为车牌识别了。

_Originally posted by @jackman01 in https://github.com/armaab/hyperlpr-train/issues/5#issuecomment-486482311_

**Comment by yuxingfafu** [comment]
哥们，有对应的训练代码么？能分享下的么？该仓库的的训练脚本跑了下有问题，跑不起来，
