### ISSUE TITLE
the trained model can not recognition the Chinese characters

### ISSUE THREAD

**Issue by cuicuizhang1989** [armaab/hyperlpr-train#2]
the recognition result can not fixed by 7 bit length, is it right ? and the trained model can not recognition the Chinese characters, what is the reason, thanks a lot .

**Comment by cuicuizhang1989** [comment]
请问 main.py 中的训练代码 我看有cnn 和 ctc 没有rnn的部分 请问是否溜掉了 还是我哪没看懂，请教作者 多谢

**Comment by armaab** [comment]
1. 字符长度可以设置，命令行参数有一个选项`-label-len`指定了标签长度。**但是**训练时只会使用固定长度的标签，即训练数据集中标签必须是一样长的。
2. 识别结果不一定是固定长度的，与输入图片有关系。
3. 原来Hyperlpr里面就没有使用RNN，是一个全卷积网络，所以训练里面自然没有RNN。

**Comment by ceceha** [comment]
请问这个网络的输出是什么?
从网络结构看,输出是长度为84的向量
但是输出应该是一个矩阵,序列长度*84. 
请问这是怎么做的?
