### ISSUE TITLE
请问网络的结构是什么样的?

### ISSUE THREAD

**Issue by ceceha** [armaab/hyperlpr-train#3]
请问这个网络的输出是什么? 
从网络结构看,输出是长度为84的向量 
但是输出应该是一个矩阵,序列长度*84. 
请问这是怎么做的?

**Comment by armaab** [comment]
输出的确是一个矩阵，不过不是序列长度*84，输出维度与输入维度有关。

**Comment by ceceha** [comment]
请问这是怎么做到的?用了滑动窗?

**Comment by armaab** [comment]
对，是滑动窗口。我这个只是训练的代码，网络结构是按照原作者的来的。原来就是滑动窗口，不过是通过一个全卷积网络实现的。

**Comment by ceceha** [comment]
太感谢了!能把论文题目告诉我吗?

**Comment by armaab** [comment]
没有论文啊，就是hyperlpr里面的。你看看网络结构就懂了。

**Comment by ceceha** [comment]
好的 谢谢~
