### ISSUE TITLE
关于export()函数

### ISSUE THREAD

**Issue by seekFire** [armaab/hyperlpr-train#4]
您好，我看到在main.py中export()函数中有调用build_model()函数， 请问这是否说明子解析器export仅仅是导出一个未训练的模型？ 如何是的话，我看模型也并不复杂，这样做的目的是什么？

**Comment by armaab** [comment]
导出的是网络结构，如果你只是使用原作者的代码进行识别的话，这个导出的模型没有用。

如果你希望修改网络结构，那么就可以将模型导出，然后在识别的时候加载进去，这样就不用修改两处（训练和识别）代码了。
