### ISSUE TITLE
模型训练完后，保存的h5文件载入hyperLPR中无法识别训练样本？

### ISSUE THREAD

**Issue by Pau1code** [armaab/hyperlpr-train#6]
训练完后的损失值已经是0.04，为什么载入hyperLPR中的e2e网络中，连训练时用的样本都无法识别？

**Comment by armaab** [comment]
根据你目前给出的信息我无法判断哪里出了问题，如果可以请你提供一下你训练好的h5文件。

**Comment by Pau1code** [comment]
这个python main.py [-num_channels 3] export -m model.h5命令行仅仅是到处未训练的网络结构吧，而训练后的模型文件应该在checkpoints文件夹里，是这个意思吧，感谢您的回答！

**Comment by Pau1code** [comment]
这个python main.py [-num_channels 3] export -m model.h5命令行仅仅是未训练的网络吧，而训练后的模型文件应该在checkpoints文件夹里，是这个意思吧，感谢您的回答！

**Comment by armaab** [comment]
对的，这个命令导出的是网络的结构（在HyperLPR中用不到）。

**Comment by armaab** [comment]
对的，这个命令导出的是网络的结构（在HyperLPR中用不到）。

**Comment by ShaneYS** [comment]
你好，有个问题请教下。

原始版本的hyperlpr使用的识别模型是softmax多标签分类，也就是ocr_plate_all_w_rnn_2.h5，可以正常使用。
我在hyperlpr_py3/e2e.py中把识别模型改为rnn+ctc识别，也就是ocr_plate_all_gru.h5，然后再次运行的时候报错：
ValueError: You are trying to load a weight file containing 13 layers into a model with 11 layers.

请问这个是什么原因？

换模型之后需要对代码进行什么修改吗

**Comment by armaab** [comment]
这个问题你应该去[HyperLPR](https://github.com/zeusees/HyperLPR)那边问。我觉得可能是因为hyperlpr_py3/e2e.py中的网络结构和你加载的那个文件的结构不一样。你要把网络结构改成GRU的。

**Comment by caisan** [comment]
> 这个python main.py [-num_channels 3] export -m model.h5命令行仅仅是未训练的网络吧，而训练后的模型文件应该在checkpoints文件夹里，是这个意思吧，感谢您的回答！

训练完成后checkpoints目录中有很多h5文件，用哪个？
