### ISSUE TITLE
Can you give an example of predicting code with the trained h5 model?

### ISSUE THREAD

**Issue by 1474123989** [armaab/hyperlpr-train#8]
By using  

model = load_model(args.m, custom_objects = {'<lambda>': lambda y_true, y_pred: y_pred}) 
classes = model.predict(img)

it just gives an error  "The model expects 4  arrays, but only received one array. Found: array with shape...".

Do you know how to solve this issue?

**Comment by armaab** [comment]
Which version of HyperLPR are you using?
