### ISSUE TITLE
请教一下，运行训练脚本一直显示loss:nan是怎么回事？

### ISSUE THREAD

**Issue by axltfytx** [armaab/hyperlpr-train#9]
您好，请教一下，batch 设置为100，运行后一直是loss：nan，batch设置多少合适？还是需要修改别的参数？

**Comment by armaab** [comment]
正常情况下不会出现这种现象，我一般将batch设置为10。可能是其它原因导致的，你提供的信息有限，我无法判断。

**Comment by szuRyan** [comment]
我用你这个代码训练batch设置为16，为什么ctc loss值一直在18徘徊不下降了。你训练时loss值是多少呢

**Comment by szuRyan** [comment]
@axltfytx 你的batch 640？太大了吧

**Comment by axltfytx** [comment]
我从10,100,120,160,640一直改，改到1024提示内存不够了，都是同样的提示，是不是刚开始是nan，训练一段时间后才不是nan？
@szuRyan

**Comment by szuRyan** [comment]
会不会是你的数据集有问题，把batch改小，最好不要超过128吧。或则改成1看看是不是数据问题。

**Comment by axltfytx** [comment]
改成1还这样，我的数据集格式没问题吧？
28张测试图片，label如下
0_粤BD00292.jpg:粤BD00292
0_粤BD04165.jpg:粤BD04165
0_粤BD04575.jpg:粤BD04575
0_粤BD40175.jpg:粤BD40175
0_粤BD41390.jpg:粤BD41390
1_粤BD04165.jpg:粤BD04165
1_粤BD10020.jpg:粤BD10020
1_粤BD40175.jpg:粤BD40175
1_粤BD41479(0001).jpg:粤BD41479
1_粤BD41480.jpg:粤BD41480
1_粤BD41482(0001).jpg:粤BD41482
1_粤BD41482(0002).jpg:粤BD41482
1_粤BD42392(0001).jpg:粤BD42392
1_粤BD43233(0002).jpg:粤BD43233
1_粤BD44183(0001).jpg:粤BD44183
1_粤BD49771(0001).jpg:粤BD49771
1_粤BD49771(0002).jpg:粤BD49771
1_粤BD55942(0001).jpg:粤BD55942
1_粤BD55942(0002).jpg:粤BD55942
1_粤BF08322(0002).jpg:粤BF08322
1_粤BF29968(0001).jpg:粤BF29968
1_粤BF29968(0002).jpg:粤BF29968
2_粤BD00292.jpg:粤BD00292
2_粤BD03519(0001).jpg:粤BD03519
2_粤BD03519(0002).jpg:粤BD03519
2_粤BD04290(0002).jpg:粤BD04290
2_粤BD04575.jpg:粤BD04575
2_粤BD04795(0001).jpg:粤BD04795
14张验证图片，label如下：
粤BF55972.jpg:粤BF55972
粤BF55975.jpg:粤BF55975
粤BF56822.jpg:粤BF56822
粤BF57119.jpg:粤BF57119
粤BF57129-1.jpg:粤BF57129
粤BF57129-2.jpg:粤BF57129
粤BF57152.jpg:粤BF57152
粤BF57186.jpg:粤BF57186
粤BF57209.jpg:粤BF57209
粤BF57287.jpg:粤BF57287
粤BF57457.jpg:粤BF57457
粤BF57475.jpg:粤BF57475
粤BF57482.jpg:粤BF57482
00000003.jpg:粤BF02325

@szuRyan 有哪些注意事项，全部大写了

**Comment by armaab** [comment]
@szuRyan 我很久没从事相关工作了，大概记得损失函数会到1以下。

**Comment by MrCuiHao** [comment]
我的车牌训练数据集大约4000张，验证集大约1000张，用此代码训练，把batch从大调到最小为1, 学习率不断调小尝试，都会一开始收敛，一会就loss=nan，epoch=1的时候就开始这样流，控制台输出效果如图所示，请问有没有解决方案，非常感谢：
![图片](https://user-images.githubusercontent.com/37323877/60405188-37586e80-9be1-11e9-9ffb-12cd339c8086.png)
